import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className={`dark:bg-slate-950 ${inter.className}`}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
